### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by AnthonyBronca** [wtorresjr/Craftsy-Etsy-Clone#164]
### Bugs breaking site
- [x] UnLiking / UnFaving lags or does not Unlike / UnFav
- [x] Products page breaks not signed in
- [x] Dead links on nav bar (categories, search bar, bell icon)
- [x] submitting a product, page breaks. Likely due to redux issues or useSelector
- [x] Duplicate items appearing on products page
- [x] Consider adding new items created to the top of splash page so that they are easier to find. 
- [x] Consider having item listing management page go from newest created to oldest created order in top-down fashion
- [x] Remove picsum from being used in the frontend, and instead utilizing images that are stored in the backend. We can use picsum to generate these seeders if needed, but they should not be fetching new information on refresh for the same item
- [x] Not returning any error messages when trying to leave a review that only has spaces
- [x] Fix the ability to update a review to only be spaces
- [x] User that is not demo can not view cart
- [x] User that is not demo can not add cart items
- [x] Unable to add items to cart from product detail page
- [x] Can not unlike certain items on the splash page
- [x] Can not like certain items on the splash page
- [x] Redux store persists after log out. This causes an issue where I can go from Demo user and see cart items, and then sign out and sign into the new user account and still see the same cart items Demo user had
- [x] On log out, user should be redirected to the splash page, all modals should close, all drop downs should close, and redux store should be clean slated without having to do a refresh
- [x]  create a 404 page that has a redirect button so that a user attempting to go to a product that doesn't exist does not get to a skeletal product page
- [x] Errors for username not existing/email not existing should be wiped out when starting to type again.
- [x] Errors should begin dynamically deleting as they pass any frontend errors
- [x] No errors are appearing on screen when name/email info is really long
- [x] update favicon to be a custom favicon
- [x] spamming likes button breaks site
- [x] checkout page does not let you uncheck mark the payment options, and you should only be able to check one option.

**Comment by wtorresjr** [comment]
Resolved and merged to dev

-  Products page breaks not signed in
-  Dead links on nav bar (categories, search bar, bell icon)
-  submitting a product, page breaks. Likely due to redux issues or useSelector
-  Duplicate items appearing on products page
-  create a 404 page that has a redirect button so that a user attempting to go to a product that doesn't exist does not get to a skeletal product page
