### ISSUE TITLE
Edit a Product

### ISSUE THREAD

**Issue by wtorresjr** [wtorresjr/Craftsy-Etsy-Clone#33]
Updates and returns an existing product.

- [x] An authenticated user is required for a successful response
- [x]  Only the seller of the product is authorized to edit
- [x]  Product record is updated in the database after request
- [x]  Product data returned includes the id, name, description, price, user_id, preview_image_url
- [x]  Error response with status 400 is given when body validations for the name, description, price, and preview_image_url are violated
- [x]  Error response with status 404 is given when a product does not exist with the provided id

**Comment by AnthonyBronca** [comment]
- [ ] Edit preview image
